### ISSUE TITLE
New Types of Spam Getting Through

### ISSUE THREAD

**Issue by SenorFusion** [bmarshall511/wordpress-zero-spam#239] opened 2021-02-26 15:00 UTC
I apologize if this is not the right place to provide this feedback.

We LOVE WP ZeroSpam and it's an invaluable tool.

Over the past few days, the spam bots have seemed to find a new way around WPZeroSpam. We've gone from 1-2 a day hitting spam folder to 100+

The main thing they seem to have in common is dropping spammy comments with spam author name / link that mentions their spam brand in the comment body but NOT using links in the comment body:

![image](https://user-images.githubusercontent.com/1929777/109316092-43af2780-7819-11eb-8571-4e2cc5c4a82a.png)

Is this new, or do I need to adjust settings somewhere? (I've follow all of the WP Zero Spam guidelines re: Wordpress itself).

**Comment by bmarshall511** [comment] 2021-02-26 15:03
@SenorFusion Perfect place to leave this kind of feedback & sorry to hear about the spam. Let's get this figured out. Can you provide me the URL where the spam is coming in from and a log in to the site so I can look into it? You can email me at me@benmarshall.me

**Comment by bmarshall511** [comment] 2021-02-26 17:07
Closing this, issue was caused by comment protection turned off in settings.

**Closed by bmarshall511** 2021-02-26 17:07 UTC
Labels: investigating
