### ISSUE TITLE
5.1.5 E_ERROR Thrown

### ISSUE THREAD

**Issue by DynAggelos** [bmarshall511/wordpress-zero-spam#278] opened 2021-11-09 15:02 UTC
After updating to 5.1.5 of the plugin, the following E_ERROR was thrown. The website in question is running the latest version of WP, and PHP 8.0.8.

```
An error of type E_ERROR was caused in line 50 of the file .../wp-content/plugins/zero-spam/core/admin/class-admin.php. Error message: Uncaught TypeError: array_intersect(): Argument #2 must be of type array, bool given in .../wp-content/plugins/zero-spam/core/admin/class-admin.php:50
Stack trace:
#0 .../wp-content/plugins/zero-spam/core/admin/class-admin.php(50): array_intersect(Array, false)
#1 .../wp-includes/class-wp-hook.php(303): ZeroSpam\Core\Admin\Admin->register_dashboard_widget('')
#2 .../wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#3 .../wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#4 .../wp-admin/includes/dashboard.php(129): do_action('wp_dashboard_se...')
#5 .../wp-admin/index.php(15): wp_dashboard_setup()
#6 {main}
  thrown
```

**Comment by bmarshall511** [comment] 2021-11-09 15:27
@DynAggelos Duplicate of https://github.com/bmarshall511/wordpress-zero-spam/issues/277, see for more info.

**Closed by bmarshall511** 2021-11-09 15:27 UTC
