### ISSUE TITLE
Exlude zero-spam.js from minification in WP Rocket plugin

### ISSUE THREAD

**Issue by g01010** [bmarshall511/wordpress-zero-spam#109] opened 2015-01-10 12:59 UTC
Hi

I noticed that when using Zero Spam with WP Rocket (on multisite), if I didn't exlude the zero-spam.min.js from being minified, users were unable to leave comments. Excluding the file in WP Rocket fixes it.

**Comment by bmarshall511** [comment] 2015-07-03 14:57
Going to need a little more information. Are you getting any JS errors?

**Comment by bmarshall511** [comment] 2016-11-21 20:29
Closing since I'm unable to reproduce and no other information has been provided.

**Closed by bmarshall511** 2016-11-21 20:29 UTC
Labels: question
